import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";
import Providers from "@/components/Providers";
import { Toaster } from "react-hot-toast";
import Ready from "@/components/Ready";
import PetCareTips from "@/components/PetCareTips";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PawsHome",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <Providers>
          <Navbar />
          {children}
          <PetCareTips></PetCareTips>
          <Ready></Ready>
          <Footer />
          <Toaster></Toaster>
        </Providers>
      </body>
    </html>
  );
}
